ANALYSIS_PROMPT = """
You are an expert customer intent analyst.
Analyze the following customer email and extract the key information in strictly valid JSON format.
Do not include markdown blocks or any text outside the JSON.

Email:
{email_body}

Output format:
{{
    "intent": "Short 2-3 word summary of what the customer wants",
    "emotion": "Customer's emotional state (e.g. Frustrated, Happy, Neutral, Angry)",
    "urgency": "High, Medium, or Low",
    "confidence": <integer from 0 to 100 representing confidence in analysis>,
    "keywords": ["list", "of", "key", "entities", "mentioned"],
    "missing_information": ["list", "of", "any", "missing", "details", "needed", "to", "resolve"],
    "summary": "One sentence summary of the customer's issue or request."
}}
"""

REPLY_PROMPT = """
You are a senior customer support specialist working for a global SaaS company. 
Read the customer's email carefully. Understand their intent and emotional tone. 
Write a professional, empathetic, and concise reply. 

If the email lacks information, politely ask for the missing details instead of making assumptions. 
Never fabricate order status, dates, or account information. 
Keep the response between 60 and 150 words, use a warm and helpful tone, and end with an offer for further assistance.

Customer Email:
{email_body}

Analysis Context:
Intent: {intent}
Emotion: {emotion}
Urgency: {urgency}

Generate the reply now:
"""

EVALUATION_PROMPT = """
You are an expert AI evaluator.
Evaluate the generated AI reply against the expected expected reply and the original customer email.
Return your evaluation in strictly valid JSON format. Do not use markdown blocks.

Customer Email:
{email_body}

Expected Reply:
{expected_reply}

Generated Reply:
{generated_reply}

Output format:
{{
    "Professionalism": {{
        "score": <int 1-10>,
        "reason": "Short reason for the score"
    }},
    "Empathy": {{
        "score": <int 1-10>,
        "reason": "Short reason for the score"
    }},
    "Grammar": {{
        "score": <int 1-10>,
        "reason": "Short reason for the score"
    }},
    "Helpfulness": {{
        "score": <int 1-10>,
        "reason": "Short reason for the score"
    }},
    "Completeness": {{
        "score": <int 1-10>,
        "reason": "Short reason for the score"
    }},
    "Hallucination Risk": {{
        "score": <int 1-10, where 10 is high risk and 1 is low risk>,
        "reason": "Short reason for the score"
    }}
}}
"""

COACH_PROMPT = """
You are an expert AI Communication Coach.
A response was generated by an AI assistant for a customer email, and it received an overall score of {score}/100.
Review the original email, the generated reply, and the expected reply.
Provide actionable feedback on why the score isn't higher, and then provide a strictly improved version of the reply.
Return strictly valid JSON format without markdown blocks.

Original Email:
{email_body}

Expected Reply:
{expected_reply}

Generated Reply:
{generated_reply}

Output format:
{{
    "Strengths": ["List", "of", "what", "was", "done", "well"],
    "Weaknesses": ["List", "of", "areas", "for", "improvement"],
    "Improved_Reply": "The newly generated, better reply that incorporates these suggestions.",
    "Expected_Score": <integer representing the expected new score out of 100>
}}
"""
